/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,js,jsx,ts,tsx}', './public/**/*.html'],
  theme: {
    extend: {
      colors: {
        clay: {
          mint: '#1B6B5A',
          'mint-400': '#3D9E88',
          'mint-500': '#2E8C77',
          'mint-600': '#1B6B5A',
          'mint-700': '#155A4B',
          'mint-dark': '#155A4B',
          'mint-light': '#A0D4C4',
          'mint-pale': '#E8F5F0',
          peach: '#C4785C',
          'peach-light': '#E8B8A0',
          'peach-pale': '#FDF3EE',
          blue: '#4A7FA5',
          'blue-light': '#8CB8D4',
          'blue-pale': '#EDF4F9',
          lavender: '#7B68A0',
          'lavender-light': '#B0A0C8',
          yellow: '#A48530',
          'yellow-light': '#D4C080',
          bg: '#FFFFFF',
          card: '#FFFFFF',
          dark: '#111827',
          text: '#374151',
          muted: '#6B7280',
          'admin-bg': '#F7F3EE',
          'admin-card': '#FFFCF8',
          'admin-dark': '#2D3A34',
          'admin-border': '#E8E2DA',
          'admin-muted': '#7A8C84',
          border: '#E5E7EB',
          teal: '#1B6B5A',
        },
      },
      borderRadius: {
        '4xl': '2rem',
        '5xl': '2.5rem',
        '6xl': '3rem',
      },
      boxShadow: {
        clay: 'var(--shadow-md)',
        'clay-sm': 'var(--shadow-sm)',
        'clay-lg': 'var(--shadow-lg)',
        'clay-xl': 'var(--shadow-xl)',
        mint: 'var(--shadow-mint)',
        peach: 'var(--shadow-peach)',
        blue: 'var(--shadow-blue)',
      },
      fontFamily: {
        sans: ['var(--font-body)'],
        serif: ['var(--font-serif)'],
      },
      fontSize: {
        xs: ['var(--fs-xs)', { lineHeight: 'var(--lh-xs)' }],
        sm: ['var(--fs-sm)', { lineHeight: 'var(--lh-sm)' }],
        base: ['var(--fs-base)', { lineHeight: 'var(--lh-base)' }],
        lg: ['var(--fs-lg)', { lineHeight: 'var(--lh-lg)' }],
        xl: ['var(--fs-xl)', { lineHeight: 'var(--lh-xl)' }],
        '2xl': ['var(--fs-2xl)', { lineHeight: 'var(--lh-2xl)' }],
        '3xl': ['var(--fs-3xl)', { lineHeight: 'var(--lh-3xl)' }],
        '4xl': ['var(--fs-4xl)', { lineHeight: 'var(--lh-4xl)' }],
        '5xl': ['var(--fs-5xl)', { lineHeight: 'var(--lh-5xl)' }],
        '6xl': ['var(--fs-6xl)', { lineHeight: 'var(--lh-6xl)' }],
        '7xl': ['var(--fs-7xl)', { lineHeight: 'var(--lh-7xl)' }],
        '8xl': ['var(--fs-8xl)', { lineHeight: 'var(--lh-8xl)' }],
        '9xl': ['var(--fs-9xl)', { lineHeight: 'var(--lh-9xl)' }],
      },
    },
  },
  plugins: [],
}
