#!/bin/sh
# Renders the working nginx.conf from a tracked template using SITE_DOMAIN and NOINDEX from .env.
# Usage: sh scripts/render-nginx.sh [https|http|bootstrap]   (default: https)
set -eu

mode="${1:-https}"
root_dir="$(cd "$(dirname "$0")/.." && pwd)"
env_file="${root_dir}/.env"

case "${mode}" in
  https) template="${root_dir}/nginx.https.conf" ;;
  http) template="${root_dir}/nginx.http.conf" ;;
  bootstrap) template="${root_dir}/nginx.bootstrap.conf" ;;
  *) echo "render-nginx: unknown mode '${mode}', expected https, http or bootstrap" >&2; exit 2 ;;
esac

read_env() {
  [ -f "${env_file}" ] || return 0
  sed -n "s/^$1=//p" "${env_file}" | tail -1 | tr -d '\r"' | sed "s/^'//; s/'\$//"
}

site_domain="${SITE_DOMAIN:-$(read_env SITE_DOMAIN)}"
noindex="${NOINDEX:-$(read_env NOINDEX)}"

if [ "${mode}" != "http" ] && [ -z "${site_domain}" ]; then
  echo "render-nginx: SITE_DOMAIN is not set in ${env_file}" >&2
  exit 1
fi

case "${site_domain}" in
  *[!A-Za-z0-9.-]*) echo "render-nginx: SITE_DOMAIN '${site_domain}' contains characters that are not allowed in a hostname" >&2; exit 1 ;;
esac

if [ "${noindex}" = "true" ]; then
  noindex_header='add_header X-Robots-Tag "noindex, nofollow" always;'
else
  noindex_header='# NOINDEX is off: no X-Robots-Tag header'
fi

output="${root_dir}/nginx.conf"
{
  echo "# GENERATED by scripts/render-nginx.sh from $(basename "${template}") — edit the template, not this file."
  sed -e "s|__SITE_DOMAIN__|${site_domain}|g" -e "s|__NOINDEX_HEADER__|${noindex_header}|g" "${template}"
} > "${output}.tmp"
# Write in place (same inode): docker bind-mounts the file, and a rename would leave the container on the old content.
cat "${output}.tmp" > "${output}"
rm -f "${output}.tmp"

if grep -q '__[A-Z_]*__' "${output}"; then
  echo "render-nginx: unreplaced placeholder left in nginx.conf" >&2
  exit 1
fi

echo "render-nginx: wrote nginx.conf from $(basename "${template}") for '${site_domain:-_}' (noindex=${noindex:-false})"
